env:
    - GO111MODULE=on
    - CGO_ENABLED=0
before:
    hooks:
        - go mod tidy
        - go mod download
builds:
    - env:
          - CGO_ENABLED=0
      # your entrypoint into your application
      main: ./main.go
      # the name of the binary that you want to generate - this will also be the binary name for when we get to homebrew...
      # Example: ms checkin <code> where ms is the name of the binary
      binary: goris

brews:
  - tap:
      owner: borischen0203
      name: homebrew-goris
    folder: Formula
    homepage: https://github.com/borischen0203/goris
    description: A tool to get gopher image!
    license: MIT
    test: |
      system "#{bin}/goreleaser -v"
    dependencies:
    - name: go
      type: optional
    - name: git
    install: |-
      bin.install "goris"

archives:
    - format: tar.gz
      format_overrides:
          - goos: windows
            format: zip
      name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
      replacements:
          amd64: 64bit
          386: 32bit
          arm: ARM
          arm64: ARM64
          darwin: macOS
          linux: Linux
          windows: Windows
          openbsd: OpenBSD
          netbsd: NetBSD
          freebsd: FreeBSD
          dragonfly: DragonFlyBSD
      files:
          - Readme.MD
          - LICENSE
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: '{{ .Tag }}-next'
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - 'README'
            - Merge pull request
            - Merge branch