env:
    - GO111MODULE=on
    - CGO_ENABLED=0
before:
    hooks:
        - go mod tidy
        - go mod download
builds:
    - env:
          - CGO_ENABLED=0
      goos:
        - linux
        - windows
        - darwin

brews:
  - name: goris
    homepage: https://github.com/borischen0203/homebrew-goris
    description: A tool to get gopher image!
    license: MIT
    tap:
        owner: borischen0203
        name: homebrew-goris

archives:
    - replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        386: i386
        amd64: x86_64
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ incpatch .Version }}-next"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'