name: go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Install libwebkit2gtk-4.0-dev
    #   run: sudo apt-get install libwebkit2gtk-4.0-dev
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

#     - name: Test
#       run: go test -v ./...