name: gorelease

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libwebkit2gtk-4.0-dev
      run: sudo apt-get install libwebkit2gtk-4.0-dev
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install libwebkit2gtk-4.0-dev
        run: sudo apt-get install libwebkit2gtk-4.0-dev
      # - name: GCC multilib
      #   run: sudo apt-get install gcc-multilib g++-multilib
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER }}
    needs: [build]